### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Address types of NameResolver 'unix' for 'localhost:50053' not supported by transport

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/grpc-example#1]
```bash
Exception in thread "main" java.lang.IllegalArgumentException: Address types of NameResolver 'unix' for 'localhost:50053' not supported by transport
        at io.grpc.internal.ManagedChannelImplBuilder.getNameResolverProvider(ManagedChannelImplBuilder.java:849)
        at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:699)
        at io.grpc.ForwardingChannelBuilder2.build(ForwardingChannelBuilder2.java:272)
        at com.dyrnq.GrpcExampleClient.main(GrpcExampleClient.java:16)

```

**Comment by dyrnq** [comment]
<https://github.com/grpc/grpc-java/issues/10826>
